// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by: packages/frontend/apps/electron/scripts/generate-types.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
export const handlersMeta = {
  "helper": {
    "helper": [
      "test"
    ]
  },
  "main": {
    "ui": [
      "handleCloseApp",
      "restartApp",
      "writeImageToClipboard",
      "openExternal",
      "showMainWindow",
      "handleThemeChange",
      "isFullScreen",
      "isMaximized",
      "handleMinimizeApp",
      "handleHideApp",
      "handleMaximizeApp"
    ]
  }
} as const;

export const eventsMeta = {
  "main": {
    "ui": [
      "maximized",
      "fullScreen"
    ]
  }
} as const;
