// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by: packages/frontend/apps/electron/scripts/generate-types.ts
/* eslint-disable @typescript-eslint/no-explicit-any */

// Utility type: remove trailing IpcMainInvokeEvent param and ensure Promise return
type EnsurePromise<T> = T extends Promise<any> ? T : Promise<T>;
export type ApiMethod<T> = T extends (...args: infer P) => infer R ? (...args: P) => EnsurePromise<R> : never;

export interface ElectronApis {
  helper: {
    test: ApiMethod<import('@video-editor/electron/entries/helper/test/test').TestService['test']>;
  };
  ui: {
    handleCloseApp: ApiMethod<import('@video-editor/electron/entries/main/misc/utils-handle.service').UtilsHandleService['handleCloseApp']>;
    restartApp: ApiMethod<import('@video-editor/electron/entries/main/misc/utils-handle.service').UtilsHandleService['restartApp']>;
    writeImageToClipboard: ApiMethod<import('@video-editor/electron/entries/main/misc/utils-handle.service').UtilsHandleService['writeImageToClipboard']>;
    openExternal: ApiMethod<import('@video-editor/electron/entries/main/misc/utils-handle.service').UtilsHandleService['openExternal']>;
    showMainWindow: ApiMethod<import('@video-editor/electron/entries/main/windows/main-window.service').MainWindowManager['show']>;
    handleThemeChange: ApiMethod<import('@video-editor/electron/entries/main/windows/main-window.service').MainWindowManager['handleThemeChange']>;
    isFullScreen: ApiMethod<import('@video-editor/electron/entries/main/windows/main-window.service').MainWindowManager['isFullScreen']>;
    isMaximized: ApiMethod<import('@video-editor/electron/entries/main/windows/main-window.service').MainWindowManager['isMaximized']>;
    handleMinimizeApp: ApiMethod<import('@video-editor/electron/entries/main/windows/main-window.service').MainWindowManager['handleMinimizeApp']>;
    handleHideApp: ApiMethod<import('@video-editor/electron/entries/main/windows/main-window.service').MainWindowManager['handleHideApp']>;
    handleMaximizeApp: ApiMethod<import('@video-editor/electron/entries/main/windows/main-window.service').MainWindowManager['handleMaximizeApp']>;
  };
}
